"""Add image_url column to Category model

Revision ID: be51d18b37ef
Revises: a42274e241a6
Create Date: 2024-03-02 08:44:14.481100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be51d18b37ef'
down_revision = 'a42274e241a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###
